// <auto-generated />
using System;
using FSquir.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FSquir.Api.Data.Migrations
{
    [DbContext(typeof(RecordsDbContext))]
    [Migration("20260215155201_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FSquir.Api.Data.PlayerBestScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AchievedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CoveragePercent")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<string>("InstallId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("RulesVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InstallId");

                    b.HasIndex("InstallId", "Level", "Seed", "RulesVersion")
                        .IsUnique();

                    b.ToTable("player_best_scores", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_best_scores_coverage", "\"CoveragePercent\" >= 0 AND \"CoveragePercent\" <= 100");
                        });
                });

            modelBuilder.Entity("FSquir.Api.Data.ScoreSubmissionLog", b =>
                {
                    b.Property<Guid>("ClientAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AchievedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CoveragePercent")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<string>("InstallId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsNewPersonalBest")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNewWorldRecord")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PlayerBestCoveragePercent")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RulesVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<decimal?>("WorldRecordCoveragePercent")
                        .HasColumnType("numeric");

                    b.Property<string>("WorldRecordHolderInstallId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("ClientAttemptId");

                    b.HasIndex("InstallId");

                    b.HasIndex("Level", "Seed", "RulesVersion");

                    b.ToTable("score_submission_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_score_submission_logs_coverage", "\"CoveragePercent\" >= 0 AND \"CoveragePercent\" <= 100");
                        });
                });

            modelBuilder.Entity("FSquir.Api.Data.WorldRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AchievedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CoveragePercent")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<string>("HolderInstallId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("RulesVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Level", "Seed", "RulesVersion")
                        .IsUnique();

                    b.ToTable("world_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_world_records_coverage", "\"CoveragePercent\" >= 0 AND \"CoveragePercent\" <= 100");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
